### ISSUE TITLE
Quantum_Genetic_Algorithm.py Not Working

### ISSUE THREAD

**Issue by gustaoliv** [DarkStarStrix/QSolvers#19]
The .\Quantum_Logistics_Solvers\Quantum_Genetic_Algorithm.py outdated, 

1. The numpy import uses numpy as np, but the code is using directly call to numpy.
2. The line 127 is not initializing the the cities variable  correctly

**Comment by DarkStarStrix** [comment]
ok I'll take a look

**Comment by DarkStarStrix** [comment]
Yeah, my bad Some of the syntax was changed; it messed up the implementation I have committed a new one with it working again If you find any more that are not working, tell me

**Comment by DarkStarStrix** [comment]
It should work now
